feat: delete class
Pearson-Advance/frontend-app-institution-portal pull request #102
Opened 2024-07-03 23:27 UTC by 01001110J

2024-07-04 16:18 UTC, AuraAlba requested changes

2024-07-04 16:18 UTC, AuraAlba commented on src/features/Courses/CourseDetailTable/columns.jsx
After select the button delet class and the spinner, I can select again delete and call the service
![deleteClass](https://github.com/Pearson-Advance/frontend-app-institution-portal/assets/36944773/a3eee139-e17d-493f-9c01-d3c4288c5904)

2024-07-05 13:45 UTC, anfbermudezme approved these changes

2024-07-05 14:33 UTC, AuraAlba approved these changes

2024-07-05 15:58 UTC, merged