initial config, is missing fix the update on reload
Pearson-Advance/frontend-app-institution-portal pull request #107
Opened 2024-07-15 21:22 UTC by 01001110J

2024-07-18 20:50 UTC, AuraAlba requested changes

2024-07-18 20:50 UTC, AuraAlba commented on src/features/Main/InstitutionSelector/index.jsx
> +import { updateSelectedInstitution } from 'features/Main/data/slice';
```suggestion

import { Row, Col } from '@edx/paragon';
import { Select } from 'react-paragon-topaz';

import { useLocation, useHistory } from 'react-router-dom';
import { useSelector, useDispatch } from 'react-redux';

import { formatSelectOptions } from 'helpers';
import { INSTITUTION_QUERY_ID } from 'features/constants';

import { updateSelectedInstitution } from 'features/Main/data/slice';
```

2024-07-18 20:50 UTC, AuraAlba commented on src/features/Main/index.jsx
I don't see the institution param when I open the platform, neither if I open a new tab using one of the links in the tables

2024-07-18 22:03 UTC, 01001110J commented on src/features/Main/index.jsx
What :face_exhaling:  could you add more details?

- Which table?
- Which url?
- This happens in the entire platform?
- This happen on slow connection?

2024-07-19 20:10 UTC, AuraAlba requested changes

2024-07-19 20:10 UTC, AuraAlba commented on src/features/Main/LinkWithQuery/index.jsx
I lost the query in the view all button in dashboard

2024-07-19 21:43 UTC, AuraAlba requested changes

2024-07-19 21:43 UTC, AuraAlba commented on src/features/Dashboard/InstructorAssignSection/ClassCard.jsx
> +    history.push(addQueryParam(`/manage-instructors/${encodeURIComponent(data?.masterCourseName)}/${encodeURIComponent(data?.className)}?classId=${data?.classId}&previous=dashboard`));
Plese add the addqueryparam in all history.push of the platform

2024-07-22 16:23 UTC, AuraAlba approved these changes

2024-07-22 16:24 UTC, anfbermudezme approved these changes

2024-07-22 17:58 UTC, merged