PADV-704 Add instructors component
Pearson-Advance/frontend-app-institution-portal pull request #11
Opened 2023-09-26 21:43 UTC by AuraAlba

### Ticket
https://agile-jira.pearson.com/browse/PADV-704

### Description
Add instructors option in menu sidebar, instructors data table

### Changes made

- [ ] Add instructors option in menu sidebar,
- [ ] Add instructors data table
- [ ] Add tests
- [ ] Align page title with table 
 
### Screenshots
![image](https://github.com/Pearson-Advance/frontend-app-institution-portal/assets/36944773/55b29e4d-6524-4e42-bbc2-f46a4861621b)

### How to test

- Clone the Institution Portal MFE
- Run npm install.
- Run npm run start
- Go to http://localhost:1980/instructors

2023-09-27 20:35 UTC, anfbermudezme requested changes

2023-09-27 20:35 UTC, anfbermudezme commented on src/features/Instructors/InstructorsPage/_test_/reducer.test.jsx
> +} from '../../actionTypes';
Could you please use absolute imports and implement it in all the components?

2023-09-27 20:35 UTC, anfbermudezme commented on src/features/Instructors/InstructorsPage/index.jsx
> +      const response = await getInstructorData(currentPage);
Could you please use CamelCaseobject? https://github.com/openedx/frontend-platform/blob/master/src/utils.js#L73. An example of use is https://github.com/Pearson-Advance/frontend-app-institution-portal/blob/master/src/features/Students/StudentsPage/index.jsx#L99.

2023-09-27 20:35 UTC, anfbermudezme commented on src/features/Instructors/InstructorsTable/columns.jsx
> +    accessor: 'instructor_name',
The accessors using CamelCaseObject will be change. Ex: `instructorName`

2023-10-02 15:25 UTC, anfbermudezme approved these changes
LGTM

2023-10-02 18:31 UTC, Squirrel18 approved these changes

2023-10-02 19:06 UTC, merged