PADV-706  Add filters to instructors table
Pearson-Advance/frontend-app-institution-portal pull request #12
Opened 2023-10-06 15:56 UTC by AuraAlba

### Ticket
https://agile-jira.pearson.com/browse/PADV-706

### Description
Add filters to instructors page

### Changes made

-  Add instructors filter component
- Adjust the service for filters
- Add tests

### Screenshots
![Screenshot from 2023-10-06 10-55-06](https://github.com/Pearson-Advance/frontend-app-institution-portal/assets/36944773/273c7175-3e1c-4d62-a6aa-6d4aa47b3c3a)

### How to test

- Clone the Institution Portal MFE
- Run npm install.
- Run npm run start
- Go to http://localhost:1980/instructors

2023-10-09 14:12 UTC, AuraAlba commented on src/features/Instructors/InstructorsTable/index.jsx
> +      <Row className="justify-content-center my-4 border-gray-300 bg-light-100 my-3">
It's for the table style, center, give margin and border style. It's the same as the student table but was missing a letter

2023-10-09 15:32 UTC, anfbermudezme approved these changes

2023-10-10 23:32 UTC, Squirrel18 requested changes

2023-10-10 23:32 UTC, Squirrel18 commented on src/features/Instructors/InstructorsFilters/index.jsx
> +
Unnecessary blank line. @AuraAlba

2023-10-11 15:06 UTC, Squirrel18 approved these changes

2023-10-11 16:02 UTC, merged