PADV-1158 - Adjust vertical height in licence inventory and instructor assignment
Pearson-Advance/frontend-app-institution-portal pull request #121
Opened 2024-10-16 22:25 UTC by sergivalero20

### Ticket

https://agile-jira.pearson.com/browse/PADV-1158

### Description

The vertical height of the instructor assignment and Licence inventory should be the same.

### Changes made

- [x] Adjust styles 

### Screenshot

![image](https://github.com/user-attachments/assets/8852a5be-6421-4904-984e-182cc9e6debe)

### How to test

- Clone the Institution Portal MFE
- Run npm install
- Run npm run start
- Go to /Dashboard

2024-10-17 16:13 UTC, AuraAlba requested changes

2024-10-17 16:34 UTC, sergivalero20 commented on src/features/Dashboard/DashboardPage/index.scss
> +  max-height: 10px;
@AuraAlba It's necessary to about this:

![image](https://github.com/user-attachments/assets/d1b54a18-c58f-4376-9d82-590c4dcf45f0)

2024-10-18 20:53 UTC, AuraAlba requested changes

2024-10-18 20:53 UTC, AuraAlba commented on src/features/Dashboard/DashboardPage/index.scss
> +  }
```suggestion
  }
  
  .license-section{
    margin-bottom: 1rem;
  }

  .instructor-assign-section {
    min-height: 200px;
  }
```
Add these styles in the media sections

2024-10-18 20:59 UTC, AuraAlba approved these changes

2024-10-18 21:51 UTC, merged