feat: new actions button redistribution in class details
Pearson-Advance/frontend-app-institution-portal pull request #127
Opened 2024-11-18 19:35 UTC by 01001110J

# Description

This PR resolves [PADV-1815](https://agile-jira.pearson.com/browse/PADV-1815)

## Change log
- New constant in constants file
- Refactor for button layout
- Added new options for dropdown

### Visual results
#### Before
![certprepcourseware-staging pearson com_certprep-manager_courses_course-v1%3AVUE%2BCS001%2BMar_ccx-v1%3AVUE%2BCS001%2BMar%2Bccx%40135_previous=classes institutionId=3](https://github.com/user-attachments/assets/e7732d87-5963-45f1-9658-aecc75efd953)

#### After
![localhost_1980_institution-portal_courses_course-v1%3Ademo%2Bdemo1%2B2020_ccx-v1%3Ademo%2Bdemo1%2B2020%2Bccx%4049_previous=classes institutionId=1 (1)](https://github.com/user-attachments/assets/107b8465-53cd-4a4e-850f-aad393098fb3)
![localhost_1980_institution-portal_courses_course-v1%3Ademo%2Bdemo1%2B2020_ccx-v1%3Ademo%2Bdemo1%2B2020%2Bccx%4049_previous=classes institutionId=1](https://github.com/user-attachments/assets/a0a24ef2-a7f0-4e78-8c76-f0b8e5508eb1)

### How to test

Clone the Institution Portal MFE
```Bash
     git clone <url>
```
Install the packages 📦.
```Bash
     npm i
```
Start project.
```Bash
     npm start
```

Finally, go to class details and see the results.

2024-11-18 23:35 UTC, sergivalero20 approved these changes

2024-11-19 14:18 UTC, AuraAlba requested changes

2024-11-19 14:18 UTC, AuraAlba commented on src/features/Classes/Class/ClassPage/Actions.jsx
> +            Assign instructor
In the case the class has instructors assigned, the label should be 'Manage instructors'

2024-11-19 19:34 UTC, AuraAlba approved these changes

2024-11-20 16:34 UTC, merged