Vue/padv 637
Pearson-Advance/frontend-app-institution-portal pull request #4
Opened 2023-08-31 14:04 UTC by cesarsilvaedunext

## Ticket
https://agile-jira.pearson.com/browse/PADV-637

## Description

This PR adds the InstitutionName component.

## Changes made
- Add DataTable component.

## Changes missing
- Tests.

2023-09-01 20:55 UTC, anfbermudezme approved these changes

2023-09-01 21:41 UTC, sergivalero20 approved these changes

2023-09-04 18:52 UTC, anfbermudezme requested changes

2023-09-04 18:52 UTC, anfbermudezme commented on src/features/Main/Header/data/_test_/api.test.js
> +
Unnecesary blank line.

2023-09-04 18:52 UTC, anfbermudezme commented on src/features/Main/Header/data/_test_/api.test.js
> +
Unnecesary blank line.

2023-09-04 20:45 UTC, Squirrel18 approved these changes

2023-09-04 23:25 UTC, merged