feat: Add file upload functionality for VSCode integration and tweak …
Pearson-Advance/frontend-app-institution-portal pull request #41
Opened 2024-02-21 19:55 UTC by 01001110J

This PR introduces a new `jsconfig.json` file. It sets the base URL for module resolution to the `src` directory, enhancing project organization and simplifying imports across JavaScript files by establishing a consistent base path ( for VsCode ).

Additionally, the `package.json` file has been updated. The modification to the `test` script now includes the `--watch` flag. This improvement enables Jest to run tests in watch mode, providing developers with immediate feedback during test development and refinement.

2024-02-21 21:03 UTC, anfbermudezme requested changes

2024-02-21 21:03 UTC, anfbermudezme commented on jsconfig.json
> +  "include": ["src"]
```suggestion
  "include": ["src"],
```

2024-02-21 21:05 UTC, AuraAlba requested changes

2024-02-21 21:05 UTC, AuraAlba commented on package.json
> +    "test": "fedx-scripts jest --coverage --passWithNoTests --watch"
```suggestion
    "test": "fedx-scripts jest --coverage --passWithNoTests"
    "test:watch": "fedx-scripts jest --coverage --passWithNoTests --watch"
```
Please add a different script for that, the test script is used in git checks and the image builder and breaks them

2024-02-22 18:54 UTC, anfbermudezme approved these changes

2024-02-22 20:10 UTC, AuraAlba approved these changes

2024-02-22 21:47 UTC, merged