feat: Instructor detail card
Pearson-Advance/frontend-app-institution-portal pull request #56
Opened 2024-03-18 21:04 UTC by 01001110J

2024-03-21 16:32 UTC, AuraAlba commented on src/features/Classes/InstructorCard/index.jsx
Class information is not loaded correctly when the class is not in the first page of the previous page

2024-03-21 16:47 UTC, AuraAlba requested changes

2024-03-21 16:47 UTC, AuraAlba commented on src/features/Classes/InstructorCard/index.jsx
Class information is not loaded correctly when the class is not in the first page of the previous page

2024-03-21 16:47 UTC, AuraAlba commented on src/features/Classes/InstructorCard/index.jsx
> +  const formatDateRange = (startDate, endDate) => {
Please create a utils file and move this function there so can be used in others components

2024-03-21 16:47 UTC, AuraAlba commented on src/features/Classes/InstructorCard/index.jsx
> +        <h4 className="text-color text-uppercase mb-3">Instructor</h4>
Please check font-size in figma. This looks bigger than is intended to be

2024-03-25 15:37 UTC, AuraAlba requested changes

2024-03-25 15:37 UTC, AuraAlba commented on src/features/Classes/InstructorCard/index.jsx
> +  const totalEnrolled = (classInfo?.numberOfStudents || 0)
Enrolled number is not updated when I invite a student

2024-03-25 15:37 UTC, AuraAlba commented on src/features/Classes/data/slice.js
> +      state.table.data = payload;
If this is not information for a table as far I can see, please store it in another part

2024-03-26 15:17 UTC, anfbermudezme requested changes

2024-03-26 19:23 UTC, AuraAlba approved these changes

2024-03-26 20:32 UTC, anfbermudezme approved these changes

2024-03-26 20:58 UTC, merged