PADV-1111 - Class redirection in Students view and Classes view
Pearson-Advance/frontend-app-institution-portal pull request #58
Opened 2024-03-19 19:50 UTC by sergivalero20

### Ticket
https://agile-jira.pearson.com/browse/PADV-1111

### Description
Add link in class column in Students View and in Clases Table to open the Class detail page.

### Changes made
- Add link to Class detail in Students View.
- Add link to Class detail in Classes View.
- Update tests.

### Screenshots
- Students Table

![image](https://github.com/Pearson-Advance/frontend-app-institution-portal/assets/73655023/f938730f-8dc5-4491-ac55-8b3291f260ac)

- Classes Table

![image](https://github.com/Pearson-Advance/frontend-app-institution-portal/assets/73655023/2cfdf9af-1626-46f2-a7cb-9d6c67edae2b)

### How to test

- Clone the Institution Portal MFE
- Go to vue/PADV-1111 branch
- Run npm install
- Run npm run start
- Go to http://localhost:1980/classes and verify the link in class column.
- Go to http://localhost:1980/students and verify the link in class name column.

2024-03-19 21:43 UTC, 01001110J approved these changes

2024-03-20 07:54 UTC, anfbermudezme requested changes

2024-03-20 07:54 UTC, anfbermudezme commented on src/features/Students/StudentsTable/columns.jsx
> +    Cell: ({ row }) => (<Link to={`/courses/${row.original.courseName}/${row.values.className}?classId=${row.original.classId}`} className="text-truncate link">{row.values.className}</Link>),
@sergivalero20 Line too long.

2024-03-20 14:56 UTC, AuraAlba approved these changes

2024-03-20 14:57 UTC, anfbermudezme approved these changes

2024-03-20 15:01 UTC, merged