PADV-1113 add action column in courses table
Pearson-Advance/frontend-app-institution-portal pull request #68
Opened 2024-04-03 14:31 UTC by AuraAlba

### Ticket
https://agile-jira.pearson.com/browse/PADV-1113

### Description
Add action column in courses table

### Changes made
Add action column for open course in LMS and add class in courses table
Update test

### Screenshots
![Screenshot from 2024-04-03 09-31-01](https://github.com/Pearson-Advance/frontend-app-institution-portal/assets/36944773/e4ae4b37-4819-457a-82d7-627a86450ba6)

### How to test
Clone the Institution Portal MFE
Run npm install.
Run npm run start
Go to http://localhost:1980/courses

2024-04-03 19:45 UTC, 01001110J requested changes

2024-04-03 19:45 UTC, 01001110J commented on src/features/Courses/CoursesTable/columns.jsx
> +    Cell: ({ row }) => {
This header shouldn't have this arrows, I think with a little css could be hidden ( not sure if this package has an api do this ) 

![e](https://github.com/Pearson-Advance/frontend-app-institution-portal/assets/52179095/2f5fa75b-bfdf-4d6f-be17-79d6c86bffc7)

2024-04-03 19:45 UTC, 01001110J commented on src/features/Courses/CoursesTable/columns.jsx
> +        <Dropdown className="dropdowntpz">
This happens to me when I only have 2 courses, the modal is being cover, maybe a little bit more `z-index` is necessary. 

![ee](https://github.com/Pearson-Advance/frontend-app-institution-portal/assets/52179095/7530240a-9644-4c9a-b57c-5996fac809f0)

2024-04-03 19:45 UTC, 01001110J commented on src/features/Courses/CoursesTable/columns.jsx
> +            <Dropdown.Item href={courseDetailsLink} target="_blank">
Missing [noopener](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel/noopener) and [noreferrer](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel/noreferrer)

```suggestion
            <Dropdown.Item href={courseDetailsLink} target="_blank" rel="noopener noreferrer">**
```

2024-04-03 19:45 UTC, 01001110J commented on src/features/Courses/CoursesTable/_test_/columns.test.jsx
> +    expect(columns).toHaveLength(6);
I would suggest to add a new test case to ensure the open can be open/closed and  if the actions are called.

2024-04-04 16:48 UTC, anfbermudezme approved these changes

2024-04-04 17:08 UTC, 01001110J approved these changes

2024-04-04 18:48 UTC, merged