fix: Sidebar router selection
Pearson-Advance/frontend-app-institution-portal pull request #69
Opened 2024-04-04 16:48 UTC by 01001110J

# Description

This PR fixes the error in the selection on the sidebar.

This PR resolves [PADV-1104](https://agile-jira.pearson.com/browse/PADV-1104)

## Change log
- Fixed error when you reload the page or use a link to go into institution portal.
- Refactor in routes.

### How to test

Clone the Institution Portal MFE
```Bash
     git clone <url>
```
Install the packages 📦.
```Bash
     npm i
```
Start project.
```Bash
     npm start
```

- Pick any section [home, instructors...], reload the page the sidebar should show the section selected.
- Follow the previous step, pick the url and open it into other tab, the sidebar should show the current selection.

2024-04-05 14:37 UTC, AuraAlba requested changes

2024-04-05 14:37 UTC, AuraAlba commented on src/features/Main/ActiveTabUpdater/index.jsx
For the first render I don't see the active tab, only when I make a second click

2024-04-05 17:17 UTC, anfbermudezme requested changes

2024-04-05 17:17 UTC, anfbermudezme commented on src/features/Main/ActiveTabUpdater/index.jsx
> +const ActiveTabUpdater = ({ children }) => {
@01001110J Following @AuraAlba Comment I seeing the same issue.

![2024-04-0519-14-21-ezgif com-video-to-gif-converter](https://github.com/Pearson-Advance/frontend-app-institution-portal/assets/30726391/6b08a188-afaf-4b2b-a5f5-8edf43141e56)

The active tab needs to be validated two times.

2024-04-08 15:30 UTC, anfbermudezme approved these changes

2024-04-08 17:10 UTC, merged