feat: Input for name and last name for instructor add modal
Pearson-Advance/frontend-app-institution-portal pull request #72
Opened 2024-04-23 22:15 UTC by 01001110J

2024-04-25 18:07 UTC, AuraAlba requested changes

2024-04-25 18:07 UTC, AuraAlba commented on src/features/Instructors/data/thunks.js
> +        errors = 'Whoa! Something went wrong, maybe the user already exist, or our server just take a break.';
This message is too familiar with the user, what should be a correct message for this case @anfbermudezme ?

2024-04-25 22:20 UTC, AuraAlba commented on src/features/Instructors/AddInstructors/index.jsx
> +const instructorReducer = (state, action) => {
For this case is enough with useState, in the case of more than 6 fields I think that reducer make sense

2024-04-26 17:57 UTC, anfbermudezme requested changes

2024-04-26 19:26 UTC, AuraAlba approved these changes

2024-04-26 19:47 UTC, anfbermudezme approved these changes

2024-04-29 17:45 UTC, merged