refactor: import sidebar from library
Pearson-Advance/frontend-app-institution-portal pull request #83
Opened 2024-05-23 16:13 UTC by 01001110J

2024-05-23 19:32 UTC, AuraAlba requested changes

2024-05-23 19:32 UTC, AuraAlba commented on src/features/Main/Sidebar/index.jsx
There is a gap between the sidebar and footer that shouldn't be there
![Screenshot from 2024-05-23 14-24-37](https://github.com/Pearson-Advance/frontend-app-institution-portal/assets/36944773/2567dd00-7c51-4526-a6f5-6de34bc3efb7)

2024-05-23 19:32 UTC, AuraAlba commented on src/features/Main/Sidebar/index.jsx
> +    label: 'License inventory',
License inventory doesn't fit in one line when is active 
![Screenshot from 2024-05-23 14-31-12](https://github.com/Pearson-Advance/frontend-app-institution-portal/assets/36944773/c0c93cdd-8ede-477e-8c88-1bf7d3f0c4c3)

2024-05-23 20:02 UTC, 01001110J commented on src/features/Main/Sidebar/index.jsx
That's product of the margin of the footer, should I remove it in this issue? @AuraAlba

2024-05-23 20:23 UTC, AuraAlba commented on src/features/Main/Sidebar/index.jsx
yes please

2024-05-27 14:39 UTC, AuraAlba requested changes

2024-05-27 14:39 UTC, AuraAlba commented on src/features/Main/index.jsx
When our change is used in all pages, we need to test all pages to verify that everything looks as it did before. In the content pages there are not space between the content and the footer, please add that in this repo to avoid other pr in the library
![Screenshot from 2024-05-27 09-33-32](https://github.com/Pearson-Advance/frontend-app-institution-portal/assets/36944773/8337e4cc-12df-4dca-87b9-34429b27237f)

2024-05-27 15:27 UTC, AuraAlba approved these changes

2024-05-27 15:28 UTC, anfbermudezme approved these changes

2024-05-27 16:17 UTC, merged