feat: redirect link to manage instructors in classes table
Pearson-Advance/frontend-app-institution-portal pull request #91
Opened 2024-06-12 20:23 UTC by 01001110J

2024-06-12 20:42 UTC, anfbermudezme approved these changes

2024-06-12 21:03 UTC, AuraAlba requested changes

2024-06-12 21:03 UTC, AuraAlba commented on src/features/Classes/ClassesTable/columns.jsx
> +            <Dropdown.Item>
You are missing the view class content item

2024-06-14 15:57 UTC, AuraAlba approved these changes

2024-06-18 21:56 UTC, merged